name: CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: archtechx/tenancy:latest

    strategy:
      matrix:
        include:
        - laravel: 9
          php: "8.0"
        - laravel: 10
          php: "8.1"

    steps:
    - uses: actions/checkout@v2
    - name: Start docker containers
      run: PHP_VERSION=${{ matrix.php }} docker-compose up -d
    - name: Install dependencies
      run: docker-compose exec -T test composer require --no-interaction "laravel/framework:^${{ matrix.laravel }}.0"
    - name: Run tests
      run: ./test
